export const MATERIALS: string[] = [
  'Acetate / Plastic',
  'Brass',
  'Canvas',
  'Cashmere',
  'Ceramic',
  'Corduroy',
  'Cotton',
  'Denim',
  'Enamel',
  'Fleece',
  'Glass',
  'Gold',
  'Knitwear',
  'Leather',
  'Linen',
  'Metal / Steel',
  'Nylon / Technical',
  'Pearls',
  'Resin',
  'Rubber',
  'Satin',
  'Silk',
  'Silver',
  'Stainless Steel',
  'Straw / Raffia',
  'Suede',
  'Synthetic / Polyester',
  'Titanium',
  'Velvet',
  'Wood',
  'Wool',
  'Other',
];

export const FILTER_MATERIALS: string[] = ['All', ...MATERIALS];
